"""Centralized constants for the Real World system.

This module contains all system-wide constants to ensure consistency
and easy maintenance across the codebase.
"""

# Feedback difference constants
DEFAULT_VISIBILITY_MARGIN = 0.9
DEFAULT_PERSISTENCE_MARGIN = 0.7
DEFAULT_TRANSFORMABILITY_MARGIN = 0.8

DEFAULT_VISIBILITY_LIQUIDITY = 0.85
DEFAULT_PERSISTENCE_LIQUIDITY = 0.6
DEFAULT_TRANSFORMABILITY_LIQUIDITY = 0.7

DEFAULT_VISIBILITY_POSITION = 0.95
DEFAULT_PERSISTENCE_POSITION = 0.8
DEFAULT_TRANSFORMABILITY_POSITION = 0.6

# Intervention side effect constants
DEFAULT_INTERVENTION_VISIBILITY = 0.8
DEFAULT_INTERVENTION_PERSISTENCE = 0.4
DEFAULT_INTERVENTION_TRANSFORMABILITY = 0.6

# Base magnitudes for intervention side effects
BASE_MAGNITUDE_REDUCE_RECURRENT = 30
BASE_MAGNITUDE_EXPAND_CHANNEL = 25
BASE_MAGNITUDE_RELEASE_ENTITY = 20
BASE_MAGNITUDE_MARGIN_INCREASE = 35
BASE_MAGNITUDE_POSITION_LIMIT = 40